Repository gopasspw/gopass, pull requests merged in 2018-05, with the labels that each got.

#761 Audit freshly generated passwords
  pkg/pwgen/pwgen.go
Labels: enhancement

#763 Use clang-format for proto files
  .travis.yml
  Makefile
  pkg/backend/crypto/xc/xcpb/xc.proto
Labels: enhancement

#766 Add getData message to jsonapi
  pkg/jsonapi/api_test.go
  pkg/jsonapi/messages.go
  pkg/jsonapi/responses.go
Labels: enhancement

#770 Add workaround for keyboard binding in Gnome
  docs/setup.md
Labels: documentation

#774 Fix tests exhausing resources
  pkg/action/create/create_test.go
  pkg/backend/crypto/xc/compress_test.go
  pkg/pwgen/pwgen.go
  pkg/pwgen/pwgen_test.go
  tests/gptest/unit.go
Labels: bug/confirmed

#775 Add gopass xc encrypt and decrypt
  commands.go
  commands_test.go
  pkg/action/xc/xc.go
Labels: backend/crypto

#776 Display GPG stderr when decrypting
  pkg/backend/crypto/gpg/cli/gpg.go
  pkg/backend/crypto/gpg/cli/keyring.go
  pkg/store/sub/recipients.go
Labels: bug

#777 Add xc streaming encryption
  NOTICE.txt
  commands.go
  pkg/action/xc/xc.go
  pkg/backend/crypto/xc/compress_test.go
  pkg/backend/crypto/xc/cpu.out
  pkg/backend/crypto/xc/stream.go
  pkg/backend/crypto/xc/stream_test.go
  pkg/jsonapi/manifest/setup.go
  vendor/github.com/alecthomas/binary/LICENSE
  vendor/github.com/alecthomas/binary/README.md
  vendor/github.com/alecthomas/binary/binary.go
  vendor/github.com/alecthomas/binary/binary_test.go
  vendor/vendor.json
Labels: backend/crypto

#780 Generate global wrapper and manifest files for JSON API
  .gitignore
  Makefile
  commands.go
  pkg/action/jsonapi.go
  pkg/action/jsonapi_test.go
  pkg/completion/fish/completion.go
  pkg/completion/zsh/completion.go
  pkg/jsonapi/manifest/constants.go
  pkg/jsonapi/manifest/location.go
  pkg/jsonapi/manifest/manifest.go
  pkg/jsonapi/manifest/setup.go
  pkg/jsonapi/manifest/setup_test.go
  pkg/jsonapi/manifest/templates.go
  pkg/jsonapi/manifest/wrapper.go
Labels: code/refactoring

#781 Improve code quality
  Makefile
  pkg/action/completion_test.go
  pkg/action/create/create_test.go
  pkg/action/jsonapi.go
  pkg/action/unclip_test.go
  pkg/action/version.go
  pkg/backend/crypto/gpg/openpgp/gpg.go
  pkg/backend/crypto/xc/encrypt_test.go
  pkg/backend/crypto/xc/keyring/pubring_test.go
  pkg/backend/crypto/xc/keyring/secring_test.go
  pkg/backend/crypto/xc/xc_test.go
  pkg/backend/url_test.go
  pkg/jsonapi/manifest/setup.go
  pkg/jsonapi/manifest/setup_test.go
  pkg/jsonapi/manifest/wrapper_test.go
  pkg/store/root/init.go
  pkg/updater/update_others.go
  pkg/updater/update_test.go
  tests/gptest/unit.go
  tests/gptest/utils.go
  tests/mockstore/store.go
Labels: code/refactoring, code/tests

#782 Improve style and test coverage
  pkg/action/clone.go
  pkg/action/git_test.go
  pkg/action/init_test.go
  pkg/action/xc/xc.go
  pkg/action/xc/xc_test.go
  pkg/backend/crypto/xc/stream.go
  pkg/backend/crypto/xc/stream_test.go
  pkg/store/sub/move.go
  tests/mockstore/store.go
Labels: code/refactoring

#783 Add some tests for generate --symbols
  pkg/action/generate_test.go
Labels: code/tests

#771 add subcommand "gopass git remote remove"
  commands.go
  commands_test.go
  pkg/action/git.go
  pkg/action/git_test.go
  pkg/backend/rcs.go
  pkg/backend/rcs/git/cli/git.go
  pkg/backend/rcs/git/cli/git_test.go
  pkg/backend/rcs/git/gogit/git.go
  pkg/backend/rcs/git/gogit/git_test.go
  pkg/backend/rcs/noop/backend.go
  pkg/backend/rcs/noop/backend_test.go
  pkg/store/root/git.go
Labels: backend/sync, enhancement

#789 Update terminal UI libs
  .errcheck.excl
  Gopkg.lock
  Makefile
  vendor/github.com/alecthomas/binary/binary_test.go
  vendor/github.com/gdamore/tcell/README.md
  vendor/github.com/gdamore/tcell/cell.go
  vendor/github.com/gdamore/tcell/color.go
  vendor/github.com/gdamore/tcell/console_win.go
  vendor/github.com/gdamore/tcell/simulation.go
  vendor/github.com/gdamore/tcell/terminfo/README.md
  vendor/github.com/gdamore/tcell/terminfo/mkdatabase.sh
  vendor/github.com/gdamore/tcell/terminfo/mkinfo.go
  vendor/github.com/gdamore/tcell/terminfo/models.txt
  vendor/github.com/gdamore/tcell/terminfo/term_Eterm.go
  vendor/github.com/gdamore/tcell/terminfo/term_Eterm_256color.go
  vendor/github.com/gdamore/tcell/terminfo/term_st.go
  vendor/github.com/gdamore/tcell/terminfo/term_st_256color.go
  vendor/github.com/gdamore/tcell/terminfo/terminfo.go
  vendor/github.com/jroimartin/gocui/README.md
  vendor/github.com/jroimartin/gocui/view.go
  vendor/github.com/lucasb-eyer/go-colorful/README.md
  vendor/github.com/nsf/termbox-go/README.md
  vendor/github.com/nsf/termbox-go/termbox_windows.go
  vendor/github.com/nsf/termbox-go/terminfo.go
  vendor/github.com/sethgrid/pester/README.md
  vendor/github.com/urfave/cli/CHANGELOG.md
  vendor/github.com/urfave/cli/README.md
  vendor/vendor.json
Labels: bug

#791 Fall back to ID in case fingerprint is unavailable
  pkg/backend/crypto/gpg/cli/export.go
  pkg/backend/crypto/gpg/cli/import.go
  pkg/store/sub/recipients.go
Labels: bug/confirmed

#794 Add --nogit compat handler
  CHANGELOG.md
  commands.go
  docs/setup.md
  pkg/action/init.go
  pkg/action/init_test.go
Labels: bug/confirmed

#796 Fix reencrypt
  pkg/store/sub/store.go
Labels: bug/confirmed

#743 implemented git credential caching
  commands.go
  commands_test.go
  pkg/action/git-credential.go
  pkg/action/git-credential_test.go
  tests/uninitialized_test.go
Labels: enhancement

#475 Adding concurrency for reencrypt
  pkg/action/config_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/context.go
  pkg/config/store_config.go
  pkg/ctxutil/ctxutil.go
  pkg/ctxutil/ctxutil_test.go
  pkg/store/sub/store.go
  pkg/store/sub/write.go
  tests/config_test.go
Labels: enhancement

#800 Add local recipient intregrity checking
  commands.go
  pkg/action/action_test.go
  pkg/action/fsck_test.go
  pkg/action/recipients.go
  pkg/backend/crypto/gpg/cli/keyring.go
  pkg/backend/crypto/gpg/key.go
  pkg/backend/crypto/gpg/key_test.go
  pkg/config/config.go
  pkg/config/io.go
  pkg/config/store_config.go
  pkg/store/root/git.go
  pkg/store/root/init.go
  pkg/store/root/mount.go
  pkg/store/root/recipients.go
  pkg/store/root/store.go
  pkg/store/store.go
  pkg/store/sub/fsck_test.go
  pkg/store/sub/list_test.go
  pkg/store/sub/move_test.go
  pkg/store/sub/recipients.go
  pkg/store/sub/recipients_test.go
  pkg/store/sub/store.go
  pkg/store/sub/store_test.go
  pkg/store/sub/templates_test.go
  pkg/store/vault/unsupported.go
  pkg/termio/ask.go
  tests/gptest/unit.go
Labels: enhancement, security

#790 Handle key=value pairs on generate and insert
  pkg/action/clihelper.go
  pkg/action/clihelper_test.go
  pkg/action/generate.go
  pkg/action/generate_test.go
  pkg/action/insert.go
  pkg/action/insert_test.go
Labels: enhancement

#802 Expand tilde in store path
  pkg/backend/storage.go
  pkg/backend/storage/fs/store.go
  pkg/backend/storage/kv/consul/store.go
  pkg/backend/storage/kv/inmem/store.go
  pkg/backend/url.go
  pkg/backend/url_test.go
  pkg/store/sub/storage.go
  pkg/store/sub/store.go
Labels: bug/confirmed

#804 Add gpg.listKeys caching
  Gopkg.lock
  NOTICE.txt
  pkg/backend/crypto/gpg/cli/gpg.go
  pkg/backend/crypto/gpg/cli/keyring.go
  pkg/store/sub/store.go
  pkg/store/sub/write.go
  vendor/github.com/hashicorp/golang-lru/.gitignore
  vendor/github.com/hashicorp/golang-lru/2q.go
  vendor/github.com/hashicorp/golang-lru/LICENSE
  vendor/github.com/hashicorp/golang-lru/README.md
  vendor/github.com/hashicorp/golang-lru/arc.go
  vendor/github.com/hashicorp/golang-lru/doc.go
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: backend/crypto/gpg, enhancement

#807 Add append mode for gopass insert
  commands.go
  pkg/action/copy_test.go
  pkg/action/hibp_test.go
  pkg/action/insert.go
  pkg/action/insert_test.go
Labels: enhancement, ux

#808 Improve release automation
  .goreleaser-upstream.yml
  .goreleaser.yml
  Makefile
  README.md
  VERSION
  docs/setup.md
Labels: packaging

#809 Add warning about the other gopass
  .github/ISSUE_TEMPLATE.md
  docs/setup.md
Labels: documentation

#811 Support external password generators
  docs/features.md
  pkg/pwgen/pwgen.go
  pkg/pwgen/pwgen_test.go
Labels: enhancement

#812 Beautify ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#813 Kill any pending gopass unclip processes
  pkg/clipboard/clipboard_others.go
Labels: bug/confirmed

#814 Add --force flag to recipients add
  commands.go
  pkg/action/recipients.go
Labels: enhancement

#817 Add gopass generate completion heuristic
  commands.go
  pkg/action/generate.go
  pkg/action/generate_test.go
Labels: enhancement

#819 Default to origin master for git pull
  commands_test.go
  pkg/action/git.go
  pkg/action/git_test.go
Labels: bug/confirmed

#820 Properly propagate RCS backend on gopass clone
  pkg/action/clone.go
Labels: bug/confirmed
