Repository gopasspw/gopass, pull requests merged in 2018-06, with the labels that each got.

#822 Codequality: add revive linter
  .revive.toml
  Makefile
  pkg/action/completion.go
  pkg/backend/crypto/gpg/openpgp/keyring.go
  pkg/backend/rcs/git/cli/config.go
  pkg/config/io_test.go
  pkg/cui/recipients.go
  pkg/jsonapi/api_test.go
  pkg/jsonapi/responses.go
  pkg/pinentry/pinentry.go
  pkg/store/sub/git.go
  pkg/store/sub/gpg.go
  pkg/store/sub/rcs.go
  pkg/store/sub/storage.go
  tests/init_test.go
  tests/jsonapi_test.go
Labels: code/refactoring

#823 Makefile: remove flag enforcing static compilation
  Makefile
Labels: enhancement

#821 Make move work recursively and across stores
  pkg/action/copy_test.go
  pkg/backend/storage/fs/store.go
  pkg/store/root/move.go
  pkg/store/root/move_test.go
  pkg/store/sub/list.go
  pkg/store/sub/move.go
  pkg/store/sub/move_test.go
  tests/copy_test.go
  tests/gptest/unit.go
  tests/move_test.go
Labels: bug/confirmed

#825 Warn if RCS backend is noop on sync
  pkg/action/sync.go
Labels: ux

#826 Add recipient integrity toggle and docs
  docs/features.md
  pkg/action/config_test.go
  pkg/config/config.go
  pkg/config/store_config.go
  pkg/store/sub/fsck_test.go
  pkg/store/sub/recipients.go
  pkg/store/sub/store.go
Labels: documentation, enhancement

#830 Fix gpg.parseColonsIdentity to handle UIDs w/o email
  pkg/backend/crypto/gpg/cli/gpg.go
  pkg/backend/crypto/gpg/cli/parse_colons.go
  pkg/backend/crypto/gpg/cli/parse_colons_test.go
  pkg/cui/recipients.go
Labels: bug/confirmed

#832 Support for special password rules
  pkg/action/create/create.go
  pkg/action/generate.go
  pkg/pwgen/pwgen.go
  pkg/pwgen/pwgen_test.go
Labels: enhancement

#840 Fix nested yaml structure serialization to json
  pkg/jsonapi/api_test.go
  pkg/jsonapi/helpers.go
  pkg/jsonapi/responses.go
Labels: bug/confirmed

#839 Force add changed files to git
  pkg/backend/rcs/git/cli/git.go
Labels: bug/confirmed

#841 Use appropriate config for list view
  pkg/action/list.go
Labels: bug/confirmed

#842 Improve create wizard
  commands.go
  pkg/action/create/create.go
  pkg/action/generate.go
  pkg/clipboard/clipboard.go
  pkg/cui/recipients.go
  pkg/fsutil/fsutil.go
Labels: ux

#846 Default to default password store dir
  pkg/action/action_test.go
  pkg/store/root/store.go
Labels: bug/confirmed

#847 Honor templates on generate
  pkg/action/generate.go
  pkg/store/root/templates.go
  pkg/store/sub/templates.go
Labels: enhancement

#848 Fix unwanted autosync on recipients save
  pkg/store/sub/move.go
  pkg/store/sub/recipients.go
  pkg/store/sub/write.go
Labels: bug/confirmed

#850 Resolve key ids before adding or removing
  commands.go
  pkg/action/recipients.go
Labels: bug/confirmed

#851 Support no-color.org
  context.go
Labels: ux

#855 Properly handle URL parse errors
  pkg/action/create/create.go
  pkg/action/create/create_test.go
Labels: bug/confirmed

#856 Trim fsck item path
  pkg/store/root/fsck.go
  pkg/store/sub/fsck.go
Labels: bug/confirmed

#860 Fix commit on move
  pkg/store/sub/move.go
Labels: bug/confirmed

#859 Improve fsck output
  pkg/action/fsck.go
  pkg/action/fsck_test.go
  pkg/backend/storage/fs/fsck.go
  pkg/ctxutil/ctxutil.go
  pkg/store/root/fsck.go
  pkg/store/sub/fsck.go
Labels: enhancement, ux

#863 Enable notifications on FreeBSD
  pkg/notify/notify_dbus.go
  pkg/notify/notify_others.go
Labels: os/bsd, ux

#865 Properly check and catch store initialization errors
  pkg/action/clone.go
  pkg/action/completion.go
  pkg/action/generate.go
  pkg/action/init.go
  pkg/jsonapi/api_test.go
  pkg/store/root/init.go
  pkg/store/root/init_test.go
  pkg/store/root/store_test.go
  pkg/store/sub/list.go
  tests/completion_test.go
Labels: bug/confirmed

#869 Enhance Dockerfile
  Dockerfile
  docs/setup.md
Labels: bug/confirmed

#883 Do not write version to config
  app.go
  pkg/action/xc/xc.go
  pkg/backend/crypto/xc/keyring/secring.go
  pkg/backend/crypto/xc/utils.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/io.go
  pkg/config/legacy.go
  pkg/store/root/store.go
Labels: enhancement

#886 Support symlinks for fs storage backend
  pkg/backend/storage/fs/store.go
Labels: backend/store, bug/confirmed

#889 Use valid crypto backend for key selection
  pkg/action/init.go
  pkg/store/root/gpg.go
Labels: backend/crypto, ux
