Repository gopasspw/gopass, pull requests merged in 2018-03, with the labels that each got.

#690 Allow notifications to be disabled
  action/audit.go
  action/config_test.go
  action/hibp.go
  action/sync.go
  action/unclip.go
  config/config.go
  config/store_config.go
  context.go
  utils/ctxutil/ctxutil.go
  utils/ctxutil/ctxutil_test.go
  utils/notify/notify_darwin.go
  utils/notify/notify_linux.go
  utils/notify/notify_others.go
  utils/notify/notify_test.go
  utils/notify/notify_windows.go
Labels: ux

#670 Add openpgp pure-Go backend
  Gopkg.lock
  Makefile
  action/clihelper.go
  backend/context.go
  backend/crypto.go
  backend/crypto/gpg/openpgp/gpg.go
  backend/crypto/gpg/openpgp/keyring.go
  backend/crypto/gpg/openpgp/utils.go
  store/sub/init.go
  store/sub/store.go
  store/sub/write.go
  utils/termio/ask.go
  vendor/golang.org/x/crypto/openpgp/clearsign/clearsign.go
Labels: backend/crypto/gpg

#692 Lookup correct remote for current branch
  backend/sync/git/cli/config.go
  backend/sync/git/cli/git.go
Labels: bug/confirmed

#695 Action clone: Default to gitcli
  action/clone.go
Labels: backend/sync, bug/confirmed

#698 Change Path to URL
  Makefile
  action/action_test.go
  action/clone.go
  action/config_test.go
  action/history_test.go
  backend/context.go
  backend/crypto.go
  backend/crypto/gpg/cli/binary.go
  backend/store.go
  backend/strings.go
  backend/sync.go
  backend/url.go
  backend/url_test.go
  commands_test.go
  config/config.go
  config/config_test.go
  config/io.go
  config/io_test.go
  config/legacy.go
  config/store_config.go
  store/root/init.go
  store/root/init_test.go
  store/root/mount.go
  store/root/store.go
  store/root/store_test.go
  store/sub/git.go
  store/sub/list_test.go
  store/sub/move_test.go
  store/sub/recipients.go
  store/sub/recipients_test.go
  store/sub/store.go
  utils/jsonapi/api_test.go
Labels: code/refactoring

#697 Implement Consul K/V storage backend
  Gopkg.lock
  backend/store.go
  backend/store/kv/consul/store.go
  backend/strings.go
  backend/url.go
  store/sub/store.go
  vendor/github.com/hashicorp/consul/LICENSE
  vendor/github.com/hashicorp/consul/api/README.md
  vendor/github.com/hashicorp/consul/api/acl.go
  vendor/github.com/hashicorp/consul/api/agent.go
  vendor/github.com/hashicorp/consul/api/api.go
  vendor/github.com/hashicorp/consul/api/catalog.go
  vendor/github.com/hashicorp/consul/api/coordinate.go
  vendor/github.com/hashicorp/consul/api/event.go
  vendor/github.com/hashicorp/consul/api/health.go
  vendor/github.com/hashicorp/consul/api/kv.go
  vendor/github.com/hashicorp/consul/api/lock.go
  vendor/github.com/hashicorp/consul/api/operator.go
  vendor/github.com/hashicorp/consul/api/operator_area.go
  vendor/github.com/hashicorp/consul/api/operator_autopilot.go
  vendor/github.com/hashicorp/consul/api/operator_keyring.go
  vendor/github.com/hashicorp/consul/api/operator_raft.go
  vendor/github.com/hashicorp/consul/api/operator_segment.go
  vendor/github.com/hashicorp/consul/api/prepared_query.go
  vendor/github.com/hashicorp/consul/api/raw.go
  vendor/github.com/hashicorp/consul/api/semaphore.go
  vendor/github.com/hashicorp/consul/api/session.go
  vendor/github.com/hashicorp/consul/api/snapshot.go
  vendor/github.com/hashicorp/consul/api/status.go
  vendor/github.com/hashicorp/consul/website/LICENSE.md
  vendor/github.com/hashicorp/go-cleanhttp/LICENSE
  vendor/github.com/hashicorp/go-cleanhttp/README.md
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-cleanhttp/doc.go
  vendor/github.com/hashicorp/go-cleanhttp/handlers.go
  vendor/github.com/hashicorp/go-rootcerts/.travis.yml
  vendor/github.com/hashicorp/go-rootcerts/LICENSE
  vendor/github.com/hashicorp/go-rootcerts/Makefile
  vendor/github.com/hashicorp/go-rootcerts/README.md
  vendor/github.com/hashicorp/go-rootcerts/doc.go
  vendor/github.com/hashicorp/go-rootcerts/rootcerts.go
  vendor/github.com/hashicorp/go-rootcerts/rootcerts_base.go
  vendor/github.com/hashicorp/go-rootcerts/rootcerts_darwin.go
  vendor/github.com/hashicorp/go-rootcerts/test-fixtures/capath-with-symlinks/securetrust.pem
  vendor/github.com/hashicorp/go-rootcerts/test-fixtures/capath-with-symlinks/thawte.pem
  vendor/github.com/hashicorp/serf/LICENSE
  vendor/github.com/hashicorp/serf/coordinate/client.go
  vendor/github.com/hashicorp/serf/coordinate/config.go
  vendor/github.com/hashicorp/serf/coordinate/coordinate.go
  vendor/github.com/hashicorp/serf/coordinate/phantom.go
  vendor/github.com/hashicorp/serf/ops-misc/debian/copyright
  vendor/github.com/hashicorp/serf/website/source/LICENSE
Labels: backend/store, enhancement

#685 Auto copy with safecontent
  action/show.go
  action/show_test.go
  store/err.go
  tests/show_test.go
Labels: enhancement

#701 Overwrite AutoSync and NoConfirm with sub store config
  action/show.go
  context.go
  store/root/mount.go
  store/root/read.go
Labels: bug/confirmed

#702 Rename backends
  action/action_test.go
  action/audit.go
  action/audit_test.go
  action/clone.go
  action/clone_test.go
  action/history_test.go
  action/init.go
  backend/context.go
  backend/crypto.go
  backend/crypto/gpg/openpgp/gpg.go
  backend/crypto/plain/backend.go
  backend/crypto/plain/backend_test.go
  backend/rcs.go
  backend/rcs/git/cli/config.go
  backend/rcs/git/cli/config_test.go
  backend/rcs/git/cli/git.go
  backend/rcs/git/cli/git_test.go
  backend/rcs/git/gogit/git.go
  backend/rcs/git/gogit/git_test.go
  backend/rcs/noop/backend.go
  backend/rcs/noop/backend_test.go
  backend/storage.go
  backend/storage/fs/store.go
  backend/storage/kv/consul/store.go
  backend/storage/kv/inmem/store.go
  backend/strings.go
  backend/sync/git/mock/git.go
  backend/url.go
  backend/url_test.go
  commands.go
  commands_test.go
  config/config_test.go
  store/root/git.go
  store/root/init.go
  store/root/init_test.go
  store/root/mount.go
  store/root/store.go
  store/root/store_test.go
  store/sub/git.go
  store/sub/git_test.go
  store/sub/gpg.go
  store/sub/init.go
  store/sub/list.go
  store/sub/list_test.go
  store/sub/move.go
  store/sub/move_test.go
  store/sub/read.go
  store/sub/recipients.go
  store/sub/recipients_test.go
  store/sub/store.go
  store/sub/store_test.go
  store/sub/templates.go
  store/sub/templates_test.go
  store/sub/write.go
  tests/gptest/unit.go
  tests/tester.go
  utils/jsonapi/api_test.go
  utils/jsonapi/messages_test.go
Labels: code/refactoring

#703 Add recipient editor when confirming recipients
  README.md
  action/clihelper.go
  action/config_test.go
  action/edit_linux.go
  action/edit_others.go
  action/edit_windows.go
  backend/context_test.go
  backend/crypto/gpg/cli/binary.go
  backend/crypto/gpg/cli/generate_test.go
  backend/crypto/gpg/cli/gpg_test.go
  backend/crypto/gpg/cli/import_test.go
  backend/crypto/gpg/cli/utils.go
  backend/crypto/gpg/cli/utils_test.go
  backend/crypto/plain/backend_test.go
  commands.go
  config/config_test.go
  config/context.go
  config/store_config.go
  store/root/store_test.go
  store/sub/recipients.go
  store/sub/write.go
  utils/ctxutil/ctxutil.go
  utils/ctxutil/ctxutil_test.go
Labels: backend/crypto, ux

#704 Backend related bugfixes
  backend/storage/fs/store.go
  backend/storage/kv/consul/store.go
  docs/backends.md
  store/root/mount.go
  store/root/store.go
  store/sub/init.go
  store/sub/list.go
  store/sub/recipients.go
  store/sub/store.go
Labels: backend/store, bug/confirmed

#706 Refactor HIBP
  action/hibp.go
  action/hibp_test.go
  commands.go
  utils/hibp/api/client.go
  utils/hibp/dump/scanner.go
Labels: code/refactoring, enhancement

#708 Add secret config store
  action/action.go
  action/action_test.go
  action/clihelper.go
  action/history_test.go
  action/init.go
  action/init_test.go
  app.go
  backend/crypto/xc/decrypt.go
  backend/crypto/xc/encrypt.go
  backend/crypto/xc/encrypt_test.go
  backend/crypto/xc/keyring/private_key.go
  backend/crypto/xc/keyring/secring.go
  backend/crypto/xc/utils.go
  backend/crypto/xc/utils_test.go
  backend/crypto/xc/xc.go
  backend/storage.go
  backend/storage/fs/store.go
  backend/storage/kv/consul/store.go
  backend/storage/kv/inmem/store.go
  commands.go
  config/config.go
  config/io.go
  config/secrets/config.go
  config/secrets/config_test.go
  store/root/git.go
  store/root/gpg.go
  store/root/init.go
  store/root/mount.go
  store/root/store.go
  store/root/store_test.go
  store/sub/crypto.go
  store/sub/init.go
  store/sub/rcs.go
  store/sub/recipients_test.go
  store/sub/storage.go
  store/sub/store.go
  store/sub/store_test.go
  store/sub/templates_test.go
  tests/jsonapi_test.go
  tests/tester.go
  utils/agent/agent.go
  utils/agent/client/client.go
  utils/agent/client/client_others.go
  utils/agent/client/client_windows.go
  utils/jsonapi/api_test.go
Labels: enhancement

#713 Document recursive copying
  action/copy.go
  action/copy_test.go
  action/insert_test.go
  commands.go
  tests/copy_test.go
Labels: bug/confirmed, documentation

#714 Implement secrets interface
  action/insert.go
  action/otp.go
  action/show.go
  store/root/git.go
  store/root/read.go
  store/root/write.go
  store/secret.go
  store/secret/secret.go
  store/sub/git.go
  store/sub/read.go
  store/sub/write.go
  utils/jsonapi/api_test.go
  utils/jsonapi/responses.go
  utils/jsonapi/responses_test.go
  utils/tpl/template.go
  utils/tpl/template_test.go
Labels: code/refactoring, enhancement

#721 Reintroduce fsck
  commands.go
  commands_test.go
  pkg/action/fsck.go
  pkg/backend/crypto.go
  pkg/backend/crypto/gpg/cli/gpg.go
  pkg/backend/crypto/gpg/cli/keyring.go
  pkg/backend/crypto/gpg/openpgp/gpg.go
  pkg/backend/crypto/plain/backend.go
  pkg/backend/crypto/xc/utils.go
  pkg/backend/storage.go
  pkg/backend/storage/fs/fsck.go
  pkg/backend/storage/fs/store.go
  pkg/backend/storage/kv/consul/store.go
  pkg/backend/storage/kv/inmem/store.go
  pkg/store/root/fsck.go
  pkg/store/root/list.go
  pkg/store/sub/fsck.go
  pkg/store/sub/recipients.go
Labels: enhancement

#722 Introduce store interface
  pkg/action/sync.go
  pkg/cui/recipients.go
  pkg/store/root/git.go
  pkg/store/root/gpg.go
  pkg/store/root/mount.go
  pkg/store/root/store.go
  pkg/store/store.go
  pkg/store/sub/git.go
  pkg/store/sub/git_test.go
  pkg/store/sub/store.go
Labels: code/refactoring

#727 Fix version
  pkg/action/version.go
  pkg/store/root/git.go
  pkg/store/root/store.go
  pkg/store/root/store_test.go
Labels: bug/confirmed

#729 Fix git init
  commands.go
  pkg/action/git.go
  pkg/action/history_test.go
  pkg/action/init.go
  pkg/notify/icon.go
  tests/mount_test.go
  tests/tester.go
Labels: bug/confirmed

#730 Use secrets config for Vault
  pkg/store/root/mount.go
  pkg/store/vault/seccfg.go
  pkg/store/vault/store.go
Labels: backend/crypto, enhancement

#733 Adopt .goreleaser.yml for latest release
  .goreleaser.yml
Labels: enhancement
