Repository gopasspw/gopass, pull requests merged in 2018-04, with the labels that each got.

#736 Switch from Chacha20Poly1305 to SecretBox (XSalsa20, Poly1305)
  docs/entropy.md
  pkg/backend/crypto/xc/README.md
  pkg/backend/crypto/xc/decrypt.go
  pkg/backend/crypto/xc/encrypt.go
  pkg/backend/crypto/xc/encrypt_test.go
Labels: backend/crypto

#739 Handle all YAML value types
  pkg/store/secret/yaml.go
  pkg/store/secret/yaml_test.go
Labels: bug/confirmed

#738 Bugfix for Secret.String() not adding a blank second line
  pkg/store/secret/secret.go
  pkg/store/secret/secret_test.go
Labels: bug/confirmed

#742 Fix handling of the --symbols flag
  commands.go
  pkg/action/generate.go
Labels: bug/confirmed

#747 Initialize before completion
  pkg/action/completion.go
Labels: bug/confirmed

#748 Improve fish completion script
  pkg/completion/fish/template.go
Labels: enhancement

#749 Allow running native hosts messaging as default when binary is renamed
  app.go
Labels: enhancement, os/windows

#757 Fix gopass init
  pkg/action/init.go
  pkg/cui/recipients.go
  pkg/store/root/init.go
  tests/init_test.go
Labels: bug/confirmed
