Repository gopasspw/gopass, pull requests merged in 2020-08, with the labels that each got.

#1478 Add additional binaries to the release
  .goreleaser.yml
  go.mod
  go.sum
Labels: ̄\_(ツ)_/ ̄

#1479 Fix git init
  internal/action/commands.go
  internal/action/rcs.go
Labels: bug

#1481 Do not crash when initializing API
  .goreleaser.yml
  Makefile
  cmd/gopass-git-credentials/main.go
  cmd/gopass-hibp/main.go
  cmd/gopass-jsonapi/main.go
  cmd/gopass-summon-provider/main.go
Labels: bug

#1482 Update dependencies
  README.md
  go.mod
  go.sum
  pkg/pwgen/cryptic.go
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: cleanup

#1483 Add new binaries to Makefile
  Makefile
  internal/action/repl.go
  pkg/gopass/api/api.go
Labels: cleanup

#1490 Do not allow saving a malformed native secret
  internal/action/edit.go
  pkg/gopass/secret/mime.go
  pkg/gopass/secret/secparse/parse.go
Labels: bug

#1493 Honor --print option for generate
  internal/action/generate.go
  internal/action/show.go
Labels: bug

#1491 Document insert -a flag
  internal/action/commands.go
Labels: bug, cleanup

#1494 Check .vimrc for possible misconfiguration
  internal/action/edit.go
  internal/editor/editor.go
Labels: feature

#1492 Retire editrecipients config option
  internal/action/config_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/context.go
  internal/config/io_test.go
  internal/config/legacy.go
  internal/cui/recipients.go
  internal/cui/recipients_test.go
  pkg/ctxutil/ctxutil.go
  pkg/ctxutil/ctxutil_test.go
  tests/config_test.go
Labels: cleanup

#1497 Use gopass-jsonapi in manifest path
  cmd/gopass-jsonapi/internal/jsonapi/manifest/wrapper.go
Labels: bug

#1498 Print config parse errors to STDERR
  internal/config/io.go
Labels: bug

#1507 Un-hide gopass otp
  internal/action/commands.go
Labels: bug

#1508 Support selecting relative revisions for show
  internal/action/commands.go
  internal/action/show.go
Labels: feature

#1511 Remove show --sync flag
  internal/action/commands.go
  internal/action/show.go
Labels: cleanup

#1509 Rename --xkcdlang and --xkcdsep
  internal/action/commands.go
  internal/action/generate.go
  internal/action/generate_test.go
Labels: cleanup

#1514 Make --qr flag complementary
  internal/action/show.go
Labels: feature

#1510 Rename show flag --force to --unsafe
  internal/action/commands.go
  internal/action/show.go
  internal/action/show_test.go
Labels: cleanup

#1513 Remove autoclip integration for gopass show
  docs/config.md
  internal/action/show.go
  internal/action/show_test.go
Labels: bug

#1515 Add age docs
  docs/backends.md
  docs/backends/age.md
Labels: documentation

#1512 Remove config option confirm
  docs/config.md
  internal/action/clihelper.go
  internal/action/config_test.go
  internal/action/init.go
  internal/action/insert.go
  internal/action/recipients.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/context.go
  internal/config/context_test.go
  internal/config/io_test.go
  internal/config/legacy.go
  internal/cui/recipients.go
  internal/cui/recipients_test.go
  internal/gptest/unit.go
  internal/store/leaf/context.go
  internal/store/leaf/context_test.go
  internal/store/leaf/write.go
  internal/store/leaf/write_test.go
  main.go
  pkg/ctxutil/ctxutil.go
  pkg/ctxutil/ctxutil_test.go
  tests/config_test.go
  tests/tester.go
Labels: cleanup

#1516 Add documentation for audit, generate, insert and show flags
  docs/commands/audit.md
  docs/commands/generate.md
  docs/commands/insert.md
  docs/commands/show.md
  docs/config.md
  internal/action/commands.go
Labels: documentation

#1518 Introduce --generator flag for gopass generate
  internal/action/commands.go
  internal/action/generate.go
  pkg/pwgen/external.go
  pkg/pwgen/pwgen.go
  pkg/pwgen/pwgen_others_test.go
Labels: cleanup

#1519 Set author date on git commit
  internal/backend/storage/gitfs/git.go
  internal/store/leaf/convert.go
  internal/store/leaf/write.go
  pkg/ctxutil/ctxutil.go
Labels: feature

#1522 Speed up gpg store initialization
  docs/backends/gpg.md
  docs/usecases/multi-store.md
  internal/backend/crypto/gpg/cli/binary.go
  internal/backend/crypto/gpg/cli/gpg.go
  internal/debug/debug.go
  internal/store/leaf/store.go
  internal/tree/root.go
Labels: bug

#1523 Add command documentation for clone, config, convert, generate and init
  docs/backends.md
  docs/backends/age.md
  docs/backends/fs.md
  docs/backends/gitfs.md
  docs/backends/gpg.md
  docs/backends/ondisk.md
  docs/commands/clone.md
  docs/commands/config.md
  docs/commands/convert.md
  docs/commands/generate.md
  docs/commands/init.md
Labels: documentation

#1528 Speed up gpg initialization
  .gitignore
  internal/backend/crypto/gpg/cli/binary.go
  main.go
  pkg/fsutil/fsutil.go
Labels: cleanup

#1529 Remove gpb and propagate commit timestamp to ondisk
  internal/backend/storage/ondisk/gpb/Makefile
  internal/backend/storage/ondisk/gpb/entry.go
  internal/backend/storage/ondisk/gpb/gpb.pb.go
  internal/backend/storage/ondisk/gpb/gpb.proto
  internal/backend/storage/ondisk/gpb/merge.go
  internal/backend/storage/ondisk/gpb/merge_test.go
  internal/backend/storage/ondisk/gpb/revision.go
  internal/backend/storage/ondisk/gpb/sort.go
  internal/backend/storage/ondisk/gpb/store.go
  internal/backend/storage/ondisk/store.go
Labels: cleanup

#1530 Add GOPASS_DISABLE_MIME to disable writing the new native secrets format
  pkg/gopass/secret/mime.go
Labels: feature

#1532 Obstruct unsafe keys in the output
  docs/features.md
  internal/action/show.go
  internal/action/show_test.go
Labels: feature

#1533 Document delete, env, find and others
  docs/commands/delete.md
  docs/commands/env.md
  docs/commands/find.md
  docs/commands/insert.md
  docs/commands/move.md
  docs/commands/show.md
  docs/commands/sync.md
  internal/action/commands.go
  internal/action/sync.go
Labels: documentation

#1536 Do not build xc by default
  Makefile
  internal/action/init_test.go
  internal/notify/icon.go
  internal/notify/notify_test.go
  main_test.go
  pkg/tempfile/mount_darwin.go
Labels: cleanup

#1540 Provide more helpful output when config contains extra fields
  internal/config/io.go
  tests/tester.go
Labels: feature

#1550 Fix Makefile
  Makefile
Labels: bug

#1555 Remove misleading config error message
  internal/config/io.go
Labels: bug

#1557 Use standard Unix directories on MacOS
  pkg/appdir/appdir_darwin.go
  pkg/appdir/appdir_xdg.go
  pkg/appdir/appdir_xdg_test.go
Labels: bug

#1556 Re-use existing .password-store directory if it exists
  internal/config/location.go
  pkg/appdir/appdir.go
Labels: bug

#1559 Refactoring List
  docs/commands/list.md
  go.mod
  go.sum
  internal/action/audit.go
  internal/action/completion.go
  internal/action/env.go
  internal/action/find.go
  internal/action/fsck.go
  internal/action/generate.go
  internal/action/grep.go
  internal/action/list.go
  internal/action/list_test.go
  internal/action/mount.go
  internal/action/recipients.go
  internal/action/repl.go
  internal/action/show_test.go
  internal/action/sync.go
  internal/action/templates.go
  internal/store/root/list_test.go
  internal/store/root/move_test.go
  internal/store/root/store_test.go
  internal/tree/node.go
  internal/tree/root_test.go
  pkg/gopass/api/api.go
  tests/list_test.go
  tests/mount_test.go
Labels: feature
