Repository gopasspw/gopass, pull requests merged in 2020-10, with the labels that each got.

#1610 Add support for inserting secrets with colons in the name
  internal/action/clihelper.go
  internal/action/clihelper_test.go
Labels: bug

#1608 Preserve content across retries during edit
  internal/action/edit.go
Labels: bug, ux

#1611 Do not duplicate K/V password key
  internal/action/edit.go
  internal/secrets/kv.go
  internal/secrets/kv_test.go
  internal/secrets/yaml.go
  internal/secrets/yaml_test.go
Labels: bug

#1618 Document interactive mode
  docs/features.md
Labels: documentation
