Repository gopasspw/gopass, pull requests merged in 2020-09, with the labels that each got.

#1568 Trim version prefix in jsonapi
  VERSION
  cmd/gopass-jsonapi/jsonapi.go
Labels: bug

#1572 Re-introduce gopass -c
  docs/commands/gopass.md
  main.go
Labels: feature

#1587 Remove xc backend
  docs/backends.md
  go.mod
  go.sum
  internal/action/xc/commands.go
  internal/action/xc/commands_test.go
  internal/action/xc/no_xc.go
  internal/action/xc/xc.go
  internal/action/xc/xc_test.go
  internal/backend/context_test.go
  internal/backend/context_xc_test.go
  internal/backend/crypto.go
  internal/backend/crypto/xc.go
  internal/backend/crypto/xc/README.md
  internal/backend/crypto/xc/askpass.go
  internal/backend/crypto/xc/askpass_test.go
  internal/backend/crypto/xc/compress.go
  internal/backend/crypto/xc/compress_test.go
  internal/backend/crypto/xc/cpu.out
  internal/backend/crypto/xc/decrypt.go
  internal/backend/crypto/xc/encrypt.go
  internal/backend/crypto/xc/encrypt_test.go
  internal/backend/crypto/xc/export.go
  internal/backend/crypto/xc/export_test.go
  internal/backend/crypto/xc/import.go
  internal/backend/crypto/xc/import_test.go
  internal/backend/crypto/xc/keyring/private_key.go
  internal/backend/crypto/xc/keyring/private_key_test.go
  internal/backend/crypto/xc/keyring/public_key.go
  internal/backend/crypto/xc/keyring/public_key_test.go
  internal/backend/crypto/xc/keyring/pubring.go
  internal/backend/crypto/xc/keyring/pubring_test.go
  internal/backend/crypto/xc/keyring/secring.go
  internal/backend/crypto/xc/keyring/secring_test.go
  internal/backend/crypto/xc/loader.go
  internal/backend/crypto/xc/stream.go
  internal/backend/crypto/xc/stream_test.go
  internal/backend/crypto/xc/utils.go
  internal/backend/crypto/xc/utils_test.go
  internal/backend/crypto/xc/xc.go
  internal/backend/crypto/xc/xc_test.go
  internal/backend/crypto/xc/xcpb/Makefile
  internal/backend/crypto/xc/xcpb/identity.go
  internal/backend/crypto/xc/xcpb/xc.pb.go
  internal/backend/crypto/xc/xcpb/xc.proto
  main.go
  xc_test.go
Labels: cleanup

#1591 Fix legacy config parsing
  internal/config/config.go
  internal/config/io.go
  internal/config/io_test.go
  internal/config/legacy.go
Labels: bug

#1579 Correcting newlines handling
  internal/action/completion.go
  internal/action/copy_test.go
  internal/action/env.go
  internal/action/find.go
  internal/action/fsck.go
  internal/action/generate.go
  internal/action/grep.go
  internal/action/insert.go
  internal/action/insert_test.go
  internal/action/recipients.go
  internal/action/repl.go
  internal/action/show.go
  internal/action/show_test.go
  internal/action/sync.go
  internal/action/templates.go
  internal/secrets/kv_test.go
  internal/secrets/plain.go
  internal/store/root/list_test.go
  internal/store/root/move_test.go
  internal/store/root/store_test.go
  pkg/gopass/api/api.go
  pkg/gopass/secret/mime.go
  pkg/gopass/secret/mime_test.go
  tests/insert_test.go
  tests/mount_test.go
  tests/show_test.go
Labels: bug
