Repository gopasspw/gopass, pull requests merged in 2021-01, with the labels that each got.

#1679 Disable gopass update
  internal/action/commands.go
  internal/updater/update.go
Labels: security

#1683 Do not search when editing a new secret
  docs/commands/edit.md
  internal/action/edit.go
Labels: bug

#1684 Remove standards violating GPG binary location caching
  internal/backend/crypto/gpg/cli/binary.go
  internal/backend/crypto/gpg/cli/binary_others.go
  internal/backend/crypto/gpg/cli/binary_windows.go
  internal/backend/crypto/gpg/cli/binary_windows_test.go
  internal/backend/crypto/gpg/cli/gpg_others.go
  internal/backend/crypto/gpg/cli/gpg_others_test.go
  internal/backend/crypto/gpg/cli/gpg_windows_test.go
  internal/backend/crypto/gpg/cli/loader.go
Labels: cleanup

#1692 Update to minio/v7
  go.mod
  go.sum
  internal/backend/storage/ondisk/remote.go
  internal/backend/storage/ondisk/store.go
  internal/backend/storage/ondisk/sync.go
Labels: cleanup

#1699 Invalidate cache after generating new GPG key
  internal/action/init.go
  internal/backend/crypto/gpg/cli/keyring.go
  internal/backend/crypto/gpg/context.go
Labels: bug

#1706 Add template functions for Bcrypt and Argon2
  docs/commands/templates.md
  internal/pwschemes/argon2i/argon2i.go
  internal/pwschemes/argon2id/argon2id.go
  internal/pwschemes/bcrypt/bcrypt.go
  internal/tpl/funcs.go
Labels: feature

#1708 Remove references to internal packages
  cmd/gopass-git-credentials/git-credential_test.go
  cmd/gopass-git-credentials/main.go
  cmd/gopass-hibp/hibp.go
  cmd/gopass-hibp/hibp_test.go
  cmd/gopass-hibp/main.go
  cmd/gopass-jsonapi/internal/jsonapi/api.go
  cmd/gopass-jsonapi/internal/jsonapi/api_fuzz.go
  cmd/gopass-jsonapi/internal/jsonapi/api_test.go
  cmd/gopass-jsonapi/jsonapi_others.go
  cmd/gopass-summon-provider/main.go
  internal/action/audit_test.go
  internal/action/binary_test.go
  internal/action/fsck.go
  internal/action/fsck_test.go
  internal/action/init.go
  internal/action/recipients.go
  internal/action/update_test.go
  internal/audit/audit.go
  internal/backend/storage/fs/fsck_test.go
  internal/out/context.go
  internal/out/context_test.go
  internal/out/print.go
  internal/out/print_test.go
  internal/store/leaf/convert.go
  internal/store/leaf/recipients_test.go
  internal/store/leaf/reencrypt.go
  internal/store/root/crypto_test.go
  internal/store/root/fsck_test.go
  internal/store/root/init_test.go
  internal/store/root/list_test.go
  internal/store/root/mount_test.go
  internal/store/root/move_test.go
  internal/store/root/rcs_test.go
  internal/store/root/read_test.go
  internal/store/root/recipients_test.go
  internal/store/root/templates_test.go
  internal/store/root/write_test.go
  internal/updater/update.go
  internal/updater/update_test.go
  main_test.go
  pkg/ctxutil/ctxutil.go
  pkg/ctxutil/ctxutil_test.go
  pkg/gopass/api/api.go
  pkg/termio/progress.go
  pkg/termio/progress_test.go
Labels: cleanup

#1714 Provide a hint to remove unknown recipients
  internal/action/recipients.go
Labels: documentation

#1719 Do not exit on non-empty second pw
  pkg/termio/ask.go
Labels: bug

#1717 Implement signature verification for self updater
  .goreleaser.yml
  go.mod
  go.sum
  internal/action/commands.go
  internal/action/update.go
  internal/action/update_test.go
  internal/action/version.go
  internal/updater/download.go
  internal/updater/extract.go
  internal/updater/github.go
  internal/updater/update.go
  internal/updater/update_others.go
  internal/updater/update_test.go
  internal/updater/update_windows.go
  internal/updater/verify.go
Labels: security

#1715 UX update
  go.mod
  internal/action/action_test.go
  internal/action/clone.go
  internal/action/clone_test.go
  internal/action/commands.go
  internal/action/completion.go
  internal/action/copy_test.go
  internal/action/create/commands.go
  internal/action/create/commands_test.go
  internal/action/delete.go
  internal/action/edit.go
  internal/action/find.go
  internal/action/fsck_test.go
  internal/action/generate.go
  internal/action/history_test.go
  internal/action/init.go
  internal/action/init_test.go
  internal/action/repl.go
  internal/action/setup.go
  internal/action/show.go
  internal/action/sync.go
  internal/action/version.go
  internal/out/print.go
  internal/store/leaf/init.go
  internal/store/leaf/recipients.go
  internal/store/leaf/reencrypt.go
  internal/store/leaf/write.go
  internal/store/root/init.go
  internal/store/root/init_test.go
  internal/store/root/mount.go
  internal/store/root/move.go
  internal/store/root/store_test.go
  main.go
  pkg/fsutil/fsutil_test.go
  pkg/gopass/api/api.go
  tests/init_test.go
Labels: ux

#1720 Remove the ondisk backend
  docs/backends.md
  docs/backends/ondisk.md
  docs/commands/convert.md
  docs/commands/init.md
  docs/commands/show.md
  go.mod
  go.sum
  internal/action/commands.go
  internal/action/config.go
  internal/action/config_test.go
  internal/backend/storage.go
  internal/backend/storage/fs/store.go
  internal/backend/storage/gitfs/storage.go
  internal/backend/storage/ondisk.go
  internal/backend/storage/ondisk/fsck.go
  internal/backend/storage/ondisk/gjs/entry.go
  internal/backend/storage/ondisk/gjs/gjs.go
  internal/backend/storage/ondisk/gjs/merge.go
  internal/backend/storage/ondisk/gjs/merge_test.go
  internal/backend/storage/ondisk/gjs/revision.go
  internal/backend/storage/ondisk/gjs/sort.go
  internal/backend/storage/ondisk/gjs/store.go
  internal/backend/storage/ondisk/loader.go
  internal/backend/storage/ondisk/rcs.go
  internal/backend/storage/ondisk/remote.go
  internal/backend/storage/ondisk/store.go
  internal/backend/storage/ondisk/sync.go
  internal/backend/storage_test.go
Labels: cleanup

#1724 Add windows support to the self updater
  go.sum
  internal/updater/extract.go
Labels: windows

#1697 Add Pinentry CLI fallback
  internal/backend/crypto/age/askpass.go
  pkg/pinentry/cli/fallback.go
Labels: age

#1727 Sync and fix out of sync flags
  internal/action/clone.go
  internal/action/commands.go
  internal/action/find.go
  internal/action/find_test.go
  internal/action/init.go
Labels: cleanup

#1734 Avoid age keyring being recreated when a wrong passphrase is entered
  internal/backend/crypto/age/age.go
  internal/backend/crypto/age/decrypt.go
  internal/backend/crypto/age/encrypt.go
  internal/backend/crypto/age/keyring.go
Labels: age

#1736 age ux fine tuning
  internal/action/grep.go
  internal/backend/crypto/age/age.go
  internal/backend/crypto/age/decrypt.go
  internal/backend/crypto/age/keyring.go
Labels: age

#1740 Add release helper
  docs/releases.md
  go.mod
  go.sum
  helpers/release/main.go
  internal/action/action.go
  internal/action/action_test.go
  internal/action/clone_test.go
  internal/action/history_test.go
  internal/action/version.go
  internal/backend/crypto.go
  internal/backend/crypto/age/age.go
  internal/backend/crypto/gpg/cli/version.go
  internal/backend/crypto/gpg/cli/version_test.go
  internal/backend/crypto/plain/backend.go
  internal/backend/crypto/plain/backend_test.go
  internal/backend/storage.go
  internal/backend/storage/fs/rcs_test.go
  internal/backend/storage/fs/store.go
  internal/backend/storage/gitfs/git.go
  internal/store/leaf/rcs_test.go
  internal/store/mockstore/inmem/store.go
  internal/updater/github.go
  internal/updater/update.go
  main.go
  main_test.go
  version.go
Labels: cleanup, documentation

#1744 Add REPL command lock
  internal/action/repl.go
  internal/backend/crypto/age/askpass.go
  internal/store/leaf/crypto.go
  internal/store/root/mount.go
Labels: age

#1745 Update screenshot
  README.md
  docs/showcase.png
  internal/action/setup.go
Labels: documentation

#1748 Allow removing uninitialized mounts
  internal/store/root/mount.go
  internal/store/root/mount_test.go
Labels: bug

#1747 Confirm passphrase when saving age keyring
  internal/backend/crypto/age/age.go
  internal/backend/crypto/age/askpass.go
  internal/backend/crypto/age/decrypt.go
  internal/backend/crypto/age/encrypt.go
  internal/backend/crypto/age/keyring.go
  internal/backend/crypto/age/ssh.go
  internal/backend/storage_test.go
  pkg/ctxutil/ctxutil.go
  pkg/pinentry/pinentry.go
Labels: age

#1749 Attempt to handle non-master git default branches
  internal/action/rcs.go
  internal/action/rcs_test.go
  internal/backend/storage/gitfs/git.go
  main_test.go
Labels: storage

#1755 Use persistent SSH connections for git operations
  docs/backends/gitfs.md
  internal/backend/storage/gitfs/config.go
  internal/backend/storage/gitfs/ssh_others.go
  internal/backend/storage/gitfs/ssh_windows.go
Labels: feature
