Repository gopasspw/gopass, pull requests merged in 2021-12, with the labels that each got.

#2054 Fixing Repology badge with new Gopass URL
  README.md
Labels: documentation, cleanup

#2055 Update pwrule generation helper to handle new breakage
  go.mod
  go.sum
  pkg/pwgen/pwrules/gen.go
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: cleanup

#2033 [Go 1.18] Use strings.Cut instead of strings.Split where feasible
  helpers/release/main.go
  internal/backend/crypto/gpg/cli/utils.go
  internal/backend/storage/gitfs/config.go
  pkg/gopass/secrets/kv.go
Labels: cleanup

#2060 Improve compatibility with passage
  go.mod
  go.sum
  internal/action/rcs.go
  internal/action/setup.go
  internal/backend/crypto/age/age.go
  internal/backend/crypto/age/askpass.go
  internal/backend/crypto/age/context.go
  internal/backend/crypto/age/decrypt.go
  internal/backend/crypto/age/encrypt.go
  internal/backend/crypto/age/identities.go
  internal/backend/crypto/age/keyring.go
  internal/backend/crypto/age/loader.go
  internal/backend/crypto/age/recipients.go
  internal/backend/crypto/age/unsupported.go
  internal/backend/crypto/gpg/cli/keyring.go
  internal/backend/crypto_test.go
  internal/backend/storage/fs/link_test.go
  internal/cache/disk.go
  internal/cache/ghssh/cache.go
  internal/cache/ghssh/github.go
  internal/cui/recipients.go
  internal/store/leaf/init.go
  internal/store/root/init.go
  internal/store/root/store.go
  pkg/appdir/appdir_xdg_test.go
  pkg/debug/version.go
  pkg/pwgen/pwrules/gen.go
  pkg/pwgen/pwrules/pwrules.go
  pkg/pwgen/validate_test.go
  pkg/tempfile/mount_darwin.go
  pkg/termio/identity_test.go
  tests/init_test.go
Labels: age

#2061 Use golang.org/x/exp/maps
  go.mod
  go.sum
  internal/action/otp.go
  internal/action/sync.go
  internal/backend/registry.go
  internal/backend/storage/gitfs/git.go
  internal/config/config_test.go
  internal/diff/diff.go
  internal/diff/diff_test.go
  internal/recipients/recipients.go
  internal/set/sorted.go
  internal/set/sorted_test.go
  internal/store/leaf/fsck.go
  internal/store/leaf/recipients.go
  internal/store/leaf/store.go
  internal/store/mockstore/inmem/store.go
Labels: cleanup

#2063 Fix fsutil.Shred and other cleanup
  internal/backend/crypto.go
  internal/backend/crypto/age/loader.go
  internal/backend/crypto/gpg/cli/loader.go
  internal/backend/crypto/plain/backend.go
  internal/backend/crypto/plain/loader.go
  internal/backend/registry.go
  internal/backend/registry_test.go
  internal/backend/storage.go
  internal/backend/storage/fs/fsck_test.go
  internal/backend/storage/fs/loader.go
  internal/backend/storage/fs/rcs_test.go
  internal/backend/storage/fs/store.go
  internal/backend/storage/gitfs/git.go
  internal/backend/storage/gitfs/git_test.go
  internal/backend/storage/gitfs/loader.go
  internal/out/print.go
  internal/store/leaf/rcs_test.go
  internal/store/leaf/store.go
  internal/store/mockstore/inmem/store.go
  internal/store/root/convert.go
  internal/store/root/fsck.go
  internal/store/root/init.go
  internal/store/root/mount.go
  internal/store/root/move.go
  internal/store/root/recipients.go
  internal/tree/root.go
  internal/tree/tree.go
  internal/updater/download.go
  internal/updater/extract.go
  pkg/clipboard/clipboard.go
  pkg/debug/debug.go
  pkg/debug/version.go
  pkg/fsutil/fsutil.go
  pkg/gopass/secrets/kv.go
  pkg/gopass/secrets/secparse/.gitignore
  pkg/gopass/secrets/secparse/parse_test.go
  pkg/gopass/secrets/yaml.go
  pkg/pwgen/pwrules/gen.go
  pkg/pwgen/pwrules/pwrules.go
  pkg/pwgen/pwrules/pwrules_gen.go
  pkg/qrcon/qrcon.go
  pkg/tempfile/mount_darwin.go
Labels: cleanup

#1809 Document reproducible builds
  Dockerfile
  Makefile
  docs/releases.md
Labels: security

#2064 Add wizard templates to gopass create
  docs/commands/create.md
  internal/action/config.go
  internal/action/config_test.go
  internal/action/create.go
  internal/action/create_test.go
  internal/backend/storage/fs/store.go
  internal/create/helpers.go
  internal/create/wizard.go
  internal/create/wizard_test.go
  internal/set/map.go
  tests/config_test.go
Labels: ux

#2074 Linting some more code
  internal/action/audit.go
  internal/action/completion.go
  internal/action/context_test.go
  internal/action/generate.go
  internal/backend/crypto/age/identities.go
  internal/backend/crypto/gpg/context_test.go
  internal/backend/registry.go
  internal/config/io.go
  internal/pwschemes/argon2i/argon2i.go
  internal/pwschemes/argon2id/argon2id.go
  internal/set/map.go
  internal/set/sorted.go
  internal/store/leaf/reencrypt.go
  pkg/gopass/secrets/plain.go
  pkg/otp/otp.go
Labels: cleanup

#2075 Migrating to Golangci-Lint
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
Labels: cleanup

#2066 Add gopass process
  docs/commands/process.md
  internal/action/commands.go
  internal/action/process.go
  internal/action/process_test.go
  main_test.go
  pkg/tempfile/file_test.go
Labels: ux

#2076 Linting some more code
  internal/action/insert.go
  internal/store/root/move.go
  tests/copy_test.go
Labels: cleanup

#2069 Cleanup backend/crypto/gpg/cli
  internal/audit/audit.go
  internal/backend/crypto/gpg/cli/binary_windows_test.go
  internal/backend/crypto/gpg/cli/decrypt.go
  internal/backend/crypto/gpg/cli/encrypt.go
  internal/backend/crypto/gpg/cli/generate_others_test.go
  internal/backend/crypto/gpg/cli/generate_windows_test.go
  internal/backend/crypto/gpg/cli/gpg.go
  internal/backend/crypto/gpg/cli/gpg_others_test.go
  internal/backend/crypto/gpg/cli/gpg_windows_test.go
  internal/backend/crypto/gpg/cli/identities.go
  internal/backend/crypto/gpg/cli/keyring.go
  internal/backend/crypto/gpg/cli/loader.go
  internal/backend/crypto/gpg/cli/recipients.go
  internal/backend/crypto/gpg/cli/recipients_test.go
  internal/backend/crypto/gpg/cli/version.go
  internal/backend/crypto/gpg/gpgconf/binary.go
  internal/backend/crypto/gpg/gpgconf/binary_others.go
  internal/backend/crypto/gpg/gpgconf/binary_windows.go
  internal/backend/crypto/gpg/gpgconf/utils.go
  internal/backend/crypto/gpg/gpgconf/utils_linux.go
  internal/backend/crypto/gpg/gpgconf/utils_linux_test.go
  internal/backend/crypto/gpg/gpgconf/utils_others.go
  internal/backend/crypto/gpg/gpgconf/utils_test.go
  internal/backend/crypto/gpg/gpgconf/utils_windows.go
  internal/backend/crypto/gpg/gpgconf/version.go
  internal/backend/crypto/gpg/gpgconf/version_test.go
  internal/store/leaf/store.go
  internal/store/root/store.go
Labels: cleanup

#2065 Improve clipboard safety
  pkg/clipboard/clipboard.go
  pkg/clipboard/clipboard_others.go
  pkg/clipboard/clipboard_windows.go
  pkg/clipboard/copy_darwin.go
  pkg/clipboard/copy_others.go
  pkg/clipboard/unclip.go
Labels: security

#2067 Add --expiry flag to gopass audit
  internal/action/audit.go
  internal/action/commands.go
  internal/audit/audit.go
Labels: feature

#2081 Remove pkg/hibp
  pkg/hibp/api/client.go
  pkg/hibp/api/client_test.go
  pkg/hibp/dump/scanner.go
  pkg/hibp/dump/scanner_test.go
Labels: cleanup

#2082 Enable golangci-lint nestif checks
  .golangci.yml
  internal/action/edit.go
  internal/action/generate.go
  internal/action/insert.go
  internal/action/show.go
  internal/action/sync.go
  internal/backend/storage.go
  internal/store/root/move.go
  pkg/clipboard/unclip.go
Labels: cleanup
