Repository gopasspw/gopass, pull requests merged in 2021-02, with the labels that each got.

#1759 Warn if throw-keyids is set
  internal/backend/crypto/age/unsupported.go
  internal/backend/crypto/gpg/cli/gpg.go
  internal/backend/crypto/gpg/cli/gpgcfg.go
Labels: gpg

#1758 Use gpgconf(1) to locate the gpg binary
  internal/backend/crypto/gpg/cli/binary_others.go
  pkg/pinentry/gpgconf/gpgconf.go
  pkg/pinentry/pinentry_darwin.go
  pkg/pinentry/pinentry_others.go
  pkg/pinentry/pinentry_windows.go
Labels: gpg

#1752 Clean up TODOs
  internal/action/env_test.go
  internal/action/rcs.go
  internal/action/rcs_test.go
  internal/action/sync.go
  internal/backend/crypto/age/age.go
  internal/backend/crypto/age/unsupported.go
  internal/backend/crypto/gpg/cli/gpg.go
  internal/backend/crypto/plain/backend.go
  internal/backend/storage.go
  internal/backend/storage/fs/rcs.go
  internal/backend/storage/fs/rcs_test.go
  internal/backend/storage/fs/store.go
  internal/cache/disk.go
  internal/cache/disk_test.go
  internal/config/location.go
  internal/store/leaf/move.go
  internal/store/leaf/rcs_test.go
  internal/store/leaf/reencrypt.go
  internal/store/leaf/write.go
  internal/store/mockstore/inmem/store.go
  internal/store/root/convert.go
  internal/store/root/crypto.go
  internal/store/root/list.go
  internal/store/root/mount.go
  internal/store/root/mount_test.go
  internal/store/root/move.go
  internal/store/root/rcs.go
  internal/store/root/read.go
  internal/store/root/recipients.go
  internal/store/root/store.go
  internal/store/root/templates.go
  internal/store/root/write.go
  main_test.go
  pkg/gopass/secrets/secparse/mime.go
  pkg/gopass/store.go
Labels: cleanup

#1772 Minor fixes to the release helper
  helpers/release/main.go
Labels: cleanup

#1778 Fix mixed case keys
  internal/action/insert_test.go
  internal/action/show.go
  internal/action/show_test.go
  pkg/gopass/secrets/kv.go
  pkg/gopass/secrets/kv_test.go
  pkg/gopass/secrets/secparse/parse_test.go
Labels: bug

#1780 Add pre-release support to the release helper
  VERSION
  helpers/release/main.go
Labels: cleanup

#1782 Add initial architecture documentation
  ARCHITECTURE.md
Labels: documentation

#1785 Do not tag during release preparation
  helpers/release/main.go
Labels: cleanup

#1786 Log keyring
  internal/updater/verify.go
Labels: cleanup

#1790 Enable updater for windows
  internal/store/leaf/reencrypt.go
  internal/updater/download.go
  internal/updater/update.go
  internal/updater/update_windows.go
  internal/updater/updateable.go
  pkg/termio/progress.go
Labels: windows

#1792 Remember when fsck was last run and remind after 90d
  docs/config.md
  internal/action/action.go
  internal/action/action_test.go
  internal/action/audit.go
  internal/action/clone_test.go
  internal/action/commands_test.go
  internal/action/completion_test.go
  internal/action/config_test.go
  internal/action/copy_test.go
  internal/action/delete_test.go
  internal/action/fsck.go
  internal/action/generate_test.go
  internal/action/grep_test.go
  internal/action/history_test.go
  internal/action/init.go
  internal/action/list_test.go
  internal/action/move_test.go
  internal/action/otp_test.go
  internal/action/recipients_test.go
  internal/action/reminder.go
  internal/action/show_test.go
  internal/action/update.go
  internal/action/version.go
  internal/action/version_test.go
  internal/backend/storage/gitfs/storage.go
  internal/reminder/reminder.go
Labels: ux

#1787 Finish first draft of the ARCHITECTURE.md
  ARCHITECTURE.md
  docs/components.dot
  docs/components.png
  internal/store/leaf/write.go
  internal/tree/root.go
Labels: documentation

#1797 Relax config checks when loading
  internal/config/io.go
  internal/config/io_test.go
  pkg/gopass/api/api.go
Labels: ̄\_(ツ)_/ ̄

#1803 Upgrade to Go 1.16
  .github/workflows/autorelease.yml
  .github/workflows/build.yml
  go.sum
  helpers/release/main.go
  internal/action/action_test.go
  internal/action/binary.go
  internal/action/binary_test.go
  internal/action/clone_test.go
  internal/action/setup.go
  internal/backend/crypto/age/decrypt.go
  internal/backend/crypto/age/encrypt.go
  internal/backend/crypto/age/ssh.go
  internal/backend/crypto/plain/backend_test.go
  internal/backend/crypto_test.go
  internal/backend/crypto_xc_test.go
  internal/backend/rcs_test.go
  internal/backend/storage/fs/fsck.go
  internal/backend/storage/fs/fsck_test.go
  internal/backend/storage/fs/store.go
  internal/backend/storage/fs/store_test.go
  internal/backend/storage/gitfs/config.go
  internal/backend/storage/gitfs/config_test.go
  internal/backend/storage/gitfs/git_test.go
  internal/backend/storage_test.go
  internal/cache/disk.go
  internal/cache/disk_test.go
  internal/config/io.go
  internal/config/io_test.go
  internal/editor/editor.go
  internal/store/leaf/crypto_test.go
  internal/store/leaf/fsck_test.go
  internal/store/leaf/init_test.go
  internal/store/leaf/list_test.go
  internal/store/leaf/move_test.go
  internal/store/leaf/rcs_test.go
  internal/store/leaf/recipients_test.go
  internal/store/leaf/store_test.go
  internal/store/leaf/templates_test.go
  internal/store/leaf/write_test.go
  internal/updater/update_test.go
  pkg/clipboard/clipboard_others.go
  pkg/fsutil/fsutil_test.go
  pkg/hibp/api/client.go
  pkg/hibp/dump/scanner_test.go
  pkg/otp/otp.go
  pkg/otp/otp_test.go
  pkg/tempfile/file.go
  pkg/tempfile/file_test.go
  tests/binary_test.go
  tests/gptest/unit.go
  tests/tester.go
Labels: cleanup

#1805 Honor Ctrl+C while waiting for user input
  internal/cui/cui.go
  pkg/termio/ask.go
  pkg/termio/reader.go
  pkg/termio/reader_test.go
Labels: bug

#1810 Remove useless Content-Type detection that trips off ClamAV
  internal/action/binary.go
Labels: cleanup
