Repository gopasspw/gopass, pull requests merged in 2021-03, with the labels that each got.

#1822 Honor --password flag
  internal/action/show.go
Labels: bug

#1817 Do not shadow directories
  internal/store/root/move.go
  internal/store/root/move_test.go
Labels: bug

#1826 Un-hide gopass grep
  internal/action/commands.go
Labels: documentation

#1827 Add manpage
  .gitignore
  Makefile
  helpers/man/main.go
Labels: documentation

#1835 Do not fail if reminder can not be initialized
  internal/action/action.go
  internal/cache/disk.go
  internal/reminder/reminder.go
  main.go
Labels: bug

#1845 Install manpage when using `make install`
  Makefile
Labels: documentation

#1838 Fix gopass update writable check
  internal/action/errors.go
  internal/updater/access_others.go
  internal/updater/access_windows.go
  internal/updater/updateable.go
Labels: bug

#1846 Fix generate --clip
  internal/action/generate.go
Labels: bug

#1847 Remove custom brew
  .goreleaser.yml
  docs/setup.md
Labels: documentation

#1855 Ensure 8-byte alignment of progressbar counters
  pkg/termio/progress.go
Labels: bug

#1853 Add post-release helper
  go.mod
  go.sum
  helpers/postrel/main.go
Labels: documentation

#1857 Tag v1.12.3
  CHANGELOG.md
  VERSION
  version.go
Labels: documentation

#1859 Use BSD install compatible install -d
  Makefile
Labels: bug

#1860 Generate manpage and completion on release
  .gitignore
  Makefile
  bash.completion
  docs/usecases/secure-otp/sign-in.puml
  fish.completion
  gopass.1
  helpers/release/main.go
  zsh.completion
Labels: cleanup

#1856 Add more debug logging
  internal/action/init.go
  internal/store/leaf/init.go
  tests/init_test.go
Labels: cleanup

#1862 Bring back --yes
  internal/action/commands.go
  main.go
Labels: bug

#1861 Update deps
  go.mod
  go.sum
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: cleanup

#1843 Allow subkeys
  internal/action/recipients.go
  internal/action/recipients_test.go
  internal/backend/crypto/gpg/cli/keyring.go
  internal/backend/crypto/gpg/key_list.go
  internal/backend/crypto/gpg/key_list_test.go
  internal/store/leaf/recipients.go
Labels: bug

#1867 Add -f flag to gopass create
  internal/action/commands.go
  internal/action/create.go
  internal/action/setup.go
  internal/cui/cui.go
Labels: feature

#1876 Move pkg/pinentry to github.com/gopasspw/pinentry
  Makefile
  go.mod
  go.sum
  internal/backend/crypto/age/askpass.go
  internal/backend/crypto/gpg/cli/binary_others.go
  pkg/pinentry/gpgconf/gpgconf.go
  pkg/pinentry/pinentry.go
  pkg/pinentry/pinentry_darwin.go
  pkg/pinentry/pinentry_others.go
  pkg/pinentry/pinentry_test.go
  pkg/pinentry/pinentry_windows.go
  zsh.completion
Labels: cleanup

#1865 Add getting started docs
  README.md
  docs/setup.md
  internal/action/clone.go
  internal/action/errors.go
  internal/action/init.go
  internal/action/setup.go
  internal/out/print.go
  pkg/debug/debug.go
Labels: cleanup, documentation

#1868 Deduplicate key selection
  internal/action/init.go
  internal/backend/crypto/gpg/key_list.go
  internal/backend/crypto/gpg/key_list_test.go
  internal/cui/recipients.go
Labels: cleanup

#1828 Add gopass ln
  docs/commands/link.md
  internal/action/audit.go
  internal/action/commands.go
  internal/action/link.go
  internal/action/list.go
  internal/backend/storage.go
  internal/backend/storage/fs/link.go
  internal/backend/storage/fs/link_test.go
  internal/backend/storage/gitfs/storage.go
  internal/store/leaf/link.go
  internal/store/leaf/link_test.go
  internal/store/mockstore/inmem/store.go
  internal/store/mockstore/store.go
  internal/store/root/link.go
  internal/tree/root.go
  main_test.go
Labels: feature

#1881 Fix ssh command for termux
  internal/backend/storage/gitfs/config.go
  internal/backend/storage/gitfs/ssh_others.go
Labels: bug

#1882 Add proper diff numbers on sync
  internal/action/sync.go
  internal/diff/diff.go
  internal/diff/diff_test.go
Labels: feature

#1887 Update deps
  go.mod
  go.sum
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: cleanup

#1886 Avoid logging credentials
  docs/config.md
  internal/action/create.go
  internal/action/env.go
  internal/action/find.go
  internal/action/fsck.go
  internal/action/generate.go
  internal/action/insert.go
  internal/action/show.go
  internal/action/update.go
  internal/out/print.go
  pkg/debug/debug.go
  pkg/gopass/secrets/kv.go
  pkg/gopass/secrets/plain.go
  pkg/gopass/secrets/secparse/parse.go
  pkg/gopass/secrets/yaml.go
Labels: security

#1890 Clean up gpg/cli
  internal/backend/crypto/gpg/cli/decrypt.go
  internal/backend/crypto/gpg/cli/encrypt.go
  internal/backend/crypto/gpg/cli/export.go
  internal/backend/crypto/gpg/cli/export_test.go
  internal/backend/crypto/gpg/cli/gpg.go
  internal/backend/crypto/gpg/cli/gpgcfg.go
  internal/backend/crypto/gpg/cli/import.go
  internal/backend/crypto/gpg/cli/import_others_test.go
  internal/backend/crypto/gpg/cli/import_windows_test.go
  internal/backend/crypto/gpg/cli/key.go
  internal/backend/crypto/gpg/cli/keyring.go
  internal/backend/crypto/gpg/cli/keyring_test.go
  internal/backend/crypto/gpg/cli/umask_others.go
  internal/backend/crypto/gpg/cli/umask_windows.go
  internal/backend/crypto/gpg/cli/utils.go
  internal/backend/crypto/gpg/cli/utils_linux.go
  internal/backend/crypto/gpg/cli/utils_others.go
  internal/backend/crypto/gpg/cli/utils_windows.go
  internal/backend/crypto/gpg/colons/parse_colons.go
  internal/backend/crypto/gpg/colons/parse_colons_test.go
  internal/backend/crypto/gpg/colons/parse_fuzz.go
  internal/backend/crypto/gpg/colons/utils.go
  pkg/fsutil/fsutil.go
Labels: cleanup

#1891 Honor create -s flag
  internal/action/create.go
Labels: bug
