Repository gopasspw/gopass, pull requests merged in 2022-10, with the labels that each got.

#2376 Include shadowed entries in flat list output
  internal/action/list_test.go
  internal/store/root/move_test.go
  internal/tree/node.go
  internal/tree/root_test.go
Labels: bug

#2372 Correctly handle key removal on Windows
  internal/store/leaf/recipients.go
Labels: windows, bug

#2378 Fix new lint issues
  .golangci.yml
  internal/tpl/template_test.go
  main.go
  pkg/gopass/api/api_test.go
  pkg/pwgen/pwgen_test.go
  pkg/qrcon/qrcon_test.go
  pkg/tempfile/file_test.go
  pkg/termio/progress_test.go
Labels: cleanup

#2383 Export and import all recipient public keys during fsck
  internal/backend/crypto/gpg/cli/keyring.go
  internal/store/leaf/context.go
  internal/store/leaf/crypto.go
  internal/store/leaf/fsck.go
Labels: gpg, ux
