Repository gopasspw/gopass, pull requests merged in 2023-04, with the labels that each got.

#2567 Update dependencies
  .github/workflows/autorelease.yml
  .github/workflows/build.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/grype.yml
  .golangci.yml
  go.mod
  go.sum
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: cleanup

#2580 [cleanup] Stop requiring RELEASE_NOTES
  CONTRIBUTING.md
  helpers/release/main.go
Labels: cleanup

#2569 feat: add core.autopush to separate push/autosync behavior
  docs/config.md
  internal/action/config_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/store/leaf/fsck.go
  internal/store/leaf/move.go
  internal/store/leaf/recipients.go
  internal/store/leaf/reencrypt.go
  internal/store/leaf/write.go
  tests/config_test.go
Labels: feature

#2510 Add ov pager
  .license-lint.yml
  docs/config.md
  go.mod
  go.sum
  internal/action/list.go
Labels: ux
