Repository gopasspw/gopass, pull requests merged in 2023-11, with the labels that each got.

#2684 Replace chzyer/readline with ergochat/readline
  go.mod
  go.sum
  internal/action/repl.go
Labels: cleanup

#2705 Create scorecard.yml
  .github/workflows/scorecard.yml
Labels: security

#2702 [cleanup] Add package description
  .goreleaser.yml
Labels: release

#2703 [feature] Add new pwgen options to capitalize and include numbers in
  .goreleaser.yml
  docs/config.md
  go.mod
  go.sum
  internal/action/generate.go
  internal/action/pwgen/commands.go
  internal/action/pwgen/pwgen.go
  pkg/pwgen/xkcdgen/pwgen.go
  pkg/pwgen/xkcdgen/pwgen_test.go
Labels: feature

#2722 [chore] Update goxkcdpwgen dependency to include my PR
  .golangci.yml
  go.mod
  go.sum
Labels: cleanup

#2716 Improved config handling and bugfixes
  docs/config.md
  internal/action/config.go
  internal/backend/storage/fs/store.go
  internal/config/config.go
  pkg/gitconfig/config.go
  pkg/gitconfig/configs.go
Labels: bug, storage

#2724 [BUGFIX] Try to always honor local config for mounts
  docs/config.md
  helpers/man/main.go
  internal/action/aliases.go
  internal/action/convert.go
  internal/action/create.go
  internal/action/generate.go
  internal/action/init.go
  internal/action/otp.go
  internal/action/recipients.go
  internal/action/reminder.go
  internal/action/repl.go
  internal/action/show.go
  internal/action/sync.go
  internal/action/unclip.go
  internal/action/version.go
  internal/backend/rcs_test.go
  internal/config/config.go
  internal/config/context.go
  internal/config/docs_test.go
  internal/config/utils.go
  internal/create/wizard.go
  internal/cui/cui.go
  internal/store/leaf/crypto.go
  internal/store/leaf/fsck.go
  internal/store/leaf/init.go
  internal/store/leaf/recipients.go
  internal/store/leaf/reencrypt.go
  internal/store/leaf/write.go
  pkg/pwgen/pwrules/aliases.go
Labels: bug, storage

#2723 Add storage.TryAdd and TryCommit methods
  internal/action/config.go
  internal/action/sync.go
  internal/backend/rcs.go
  internal/backend/storage/fossilfs/fossil.go
  internal/backend/storage/fs/rcs.go
  internal/backend/storage/gitfs/git.go
  internal/create/templates.go
  internal/create/wizard_test.go
  internal/store/leaf/fsck.go
  internal/store/leaf/move.go
  internal/store/leaf/recipients.go
  internal/store/leaf/reencrypt.go
  internal/store/leaf/templates.go
  internal/store/leaf/write.go
  internal/store/mockstore/inmem/store.go
  internal/store/root/move.go
Labels: cleanup

#2726 Tag v1.15.10
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
  gopass.1
  pkg/pwgen/pwrules/pwrules_gen.go
  version.go
  zsh.completion
Labels: release
