Repository gopasspw/gopass, pull requests merged in 2023-07, with the labels that each got.

#2617 [Fix] Using the correct env prefix for env settings
  internal/config/config.go
  internal/config/config_test.go
Labels: bug

#2624 Update dependencies
  go.mod
  go.sum
  internal/backend/crypto/age/ssh.go
  pkg/gitconfig/config_test.go
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: cleanup

#2626 Provide a global nosync option to turn off auto-sync
  internal/action/commands.go
  internal/action/init.go
Labels: cleanup

#2627 Only show desktop notification if sync produced any differences
  internal/action/sync.go
Labels: ux
