Repository gopasspw/gopass, pull requests merged in 2023-01, with the labels that each got.

#2492 Improve fsck handling and output
  .golangci.yml
  internal/action/delete.go
  internal/action/edit.go
  internal/action/generate.go
  internal/action/insert.go
  internal/action/link_test.go
  internal/action/merge.go
  internal/backend/storage/fs/store.go
  internal/queue/background.go
  internal/store/err.go
  internal/store/leaf/crypto.go
  internal/store/leaf/fsck.go
  internal/store/leaf/link.go
  internal/store/leaf/move.go
  internal/store/leaf/recipients.go
  internal/store/leaf/reencrypt.go
  internal/store/leaf/templates.go
  internal/store/leaf/write.go
  internal/store/root/move.go
  pkg/ctxutil/ctxutil.go
  pkg/ctxutil/ctxutil_test.go
  pkg/ctxutil/helper.go
Labels: cleanup

#2502 Add --create flag to gopass mounts add
  internal/action/commands.go
  internal/action/mount.go
  internal/backend/storage/fs/store.go
  pkg/fsutil/fsutil.go
Labels: feature, bug

#2505 Use custom multi error type for fsck instead of string concat
  internal/store/leaf/fsck.go
  pkg/ctxutil/ctxutil.go
Labels: cleanup

#2508 Improve gopass audit HTML output
  internal/action/audit.go
  internal/action/commands.go
  internal/audit/audit.go
  internal/audit/output.go
  internal/audit/output_test.go
  internal/audit/report.go
  internal/audit/report_test.go
  internal/tpl/funcs.go
Labels: ux

#2509 Tag v1.15.3
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
  gopass.1
  pkg/pwgen/pwrules/pwrules_gen.go
  version.go
  zsh.completion
Labels: release
