Repository gopasspw/gopass, pull requests merged in 2024-03, with the labels that each got.

#2823 [bugfix] Fix NPE when using recipients completion
  internal/action/recipients.go
  internal/store/leaf/store.go
Labels: bug

#2824 [bugfix] Use Go 1.22.0 instead of Go 1.22 to fix CodeQL
  go.mod
Labels: bug

#2814 Initial support of FIDO2 credential creation
  pkg/passkey/passkey.go
  pkg/passkey/passkey_test.go
Labels: feature

#2821 [feat] Allow supression of password generation in create templates
  docs/commands/create.md
  internal/create/wizard.go
  internal/create/wizard_test.go
  tests/audit_test.go
Labels: feature

#2822 [feat] Add .gopass-audit-ignore support to ignore secrets from audits
  docs/commands/audit.md
  internal/action/audit.go
  internal/audit/excludes.go
Labels: feature

#2820 [bugfix] Bring back audit summary
  internal/action/audit.go
  internal/action/audit_test.go
  internal/action/commands.go
  internal/audit/output.go
  internal/audit/report.go
  internal/backend/storage/fs/rcs.go
  internal/backend/storage/fs/rcs_test.go
  internal/store/leaf/convert.go
  internal/store/leaf/rcs_test.go
  internal/store/root/rcs_test.go
  main_test.go
  tests/audit_test.go
  zsh.completion
Labels: ux

#2832 [bugfix] Warn if trying to use fscopy inside the store
  internal/action/binary.go
Labels: bug, ux

#2834 Tag v1.15.12
  CHANGELOG.md
  VERSION
  go.mod
  go.sum
  gopass.1
  pkg/pwgen/pwrules/pwrules_gen.go
  version.go
Labels: release

#2848 [bugfix] Default to true for core.exportkeys even in substores
  internal/action/generate.go
  internal/action/otp.go
  internal/action/show.go
  internal/action/sync.go
  internal/action/version.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/utils.go
  internal/config/utils_test.go
  internal/store/leaf/recipients.go
  main.go
Labels: bug, cleanup

#2849 [bugfix] Fix loading of git configs
  internal/action/init.go
  internal/config/config.go
  pkg/appdir/appdir.go
  pkg/appdir/appdir_windows.go
  pkg/appdir/appdir_xdg.go
  pkg/gitconfig/config.go
  pkg/gitconfig/configs.go
  pkg/gitconfig/gitconfig.go
  pkg/gitconfig/gitconfig_others.go
  pkg/gitconfig/gitconfig_windows.go
  pkg/termio/identity_test.go
Labels: bug

#2851 [feat] Add verbosity levels to the debug package
  docs/config.md
  internal/tree/node.go
  internal/tree/root.go
  pkg/debug/debug.go
  pkg/debug/debug_test.go
  pkg/gitconfig/config.go
  pkg/gitconfig/configs.go
Labels: feature

#2852 [fix] Pass remote, if given, to local init as well
  internal/action/commands.go
  internal/action/setup.go
  internal/config/config.go
  internal/config/legacy.go
  internal/env/env_darwin.go
  pkg/fsutil/fsutil.go
  pkg/gitconfig/config.go
  pkg/gitconfig/configs.go
Labels: bug, ux
