Repository gopasspw/gopass, pull requests merged in 2024-10, with the labels that each got.

#2960 [FEATURE] Adding support for `age.Plugin` identities
  docs/backends/age.md
  go.mod
  go.sum
  internal/action/init.go
  internal/backend/crypto/age/age.go
  internal/backend/crypto/age/clientUI.go
  internal/backend/crypto/age/commands.go
  internal/backend/crypto/age/decrypt.go
  internal/backend/crypto/age/encrypt.go
  internal/backend/crypto/age/identities.go
  internal/backend/crypto/age/identities_test.go
  internal/backend/crypto/age/recipients.go
  internal/backend/crypto/age/ssh.go
  internal/cache/disk.go
  internal/cache/ghssh/github.go
  internal/store/leaf/fsck.go
  main_test.go
Labels: age

#2969 Empty Email check implemented
  internal/action/setup.go
Labels: Hacktoberfest

#2970 [FEATURE] Allow for non-interactive age setup
  .github/workflows/autorelease.yml
  .github/workflows/build.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/grype.yml
  docs/backends/age.md
  docs/config.md
  go.mod
  internal/action/action_test.go
  internal/action/copy.go
  internal/action/copy_test.go
  internal/action/generate.go
  internal/action/setup.go
  internal/action/setup_test.go
  internal/audit/audit.go
  internal/backend/crypto/age/identities.go
  internal/backend/crypto/age/loader.go
  internal/store/root/store.go
  main.go
  pkg/clipboard/clipboard.go
  pkg/clipboard/clipboard_others.go
  pkg/clipboard/clipboard_test.go
  pkg/clipboard/clipboard_windows.go
  pkg/clipboard/copy_darwin.go
  pkg/clipboard/unclip.go
  pkg/ctxutil/ctxutil.go
  pkg/fsutil/fsutil.go
  pkg/gitconfig/gitconfig_test.go
  pkg/pwgen/pwrules/pwrules.go
  pkg/pwgen/rand.go
  pkg/termio/progress.go
  pkg/termio/progress_test.go
Labels: age

#2971 chore: Update dependencies
  Makefile
  go.mod
  go.sum
  internal/action/copy.go
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: cleanup

#2972 [n/a] Correcting mistake in search+replace
  pkg/clipboard/clipboard.go
  pkg/clipboard/clipboard_windows.go
  pkg/clipboard/copy_darwin.go
  pkg/clipboard/unclip.go
Labels: cleanup

#2975 [FEATURE] Ask for setup if not initialized
  internal/action/init.go
Labels: Hacktoberfest
