Repository gopasspw/gopass, pull requests merged in 2025-04, with the labels that each got.

#3113 Allow connections to Ubuntu repository hosts
  .github/workflows/build.yml
Labels: bug

#3120 [chore] Update dependencies
  go.mod
  go.sum
  pkg/pwgen/pwrules/pwrules_gen.go
Labels: dependencies

#3122 [chore] Migrate goreleaser config to v2
  .goreleaser.yml
  Makefile
  zsh.completion
Labels: release

#3123 [feat] Replace clipboard library to support wl-copy args
  go.mod
  go.sum
  internal/action/create_test.go
  internal/action/show_test.go
  main_test.go
  pkg/clipboard/clipboard.go
  pkg/clipboard/clipboard_test.go
  pkg/clipboard/copy_darwin.go
  pkg/clipboard/copy_others.go
  pkg/clipboard/unclip.go
  tests/gptest/gunit.go
  tests/gptest/unit.go
Labels: feature

#3127 [feat] Add unconditional includes for gitconfig
  .license-lint.yml
  internal/config/docs_test.go
  pkg/gitconfig/config.go
  pkg/gitconfig/config_test.go
Labels: feature

#3128 [feat] Add conditional includes for gitconfig
  pkg/gitconfig/config.go
  pkg/gitconfig/config_test.go
Labels: feature

#3133 [feat] Remove expensive and unmaintained zxcvbn-go strength checker
  docs/commands/audit.md
  go.mod
  go.sum
  internal/audit/audit.go
  internal/backend/crypto/age/askpass.go
  tests/audit_test.go
Labels: cleanup
